name: "GitHub App Tokenizer"
description: "Action to generate GitHub App installation token"
inputs:
  version:
    description: "A version to install"
    default: "0.1.0"
  installation_id:
    description: "GitHub Apps Installation ID"
  app_id:
    description: "GitHub Apps App ID"
  private_key:
    description: "GitHub Apps Private Key"

outputs:
  github_app_token:
    description: "Generated GitHub Token"
    value: ${{ steps.github_app_tknzr.outputs.output_token }}

runs:
  using: "composite"
  steps:
    - run: |
        curl -sSLf https://raw.githubusercontent.com/diegosz/github_app_tknzr/main/install-via-release.sh | bash -s -- -v v${{ inputs.version }}
        sudo cp github_app_tknzr /usr/local/bin
      shell: bash
    - id: github_app_tknzr
      run: |
        T=$(mktemp)
        trap "rm -f $T" 1 2 3 15
        env GITHUB_PRIV_KEY="${{ inputs.private_key }}" github_app_tknzr -app-id ${{ inputs.app_id }} -inst-id ${{ inputs.installation_id }} > $T
        echo "output_token=$(cat $T)" >> $GITHUB_OUTPUT
      shell: bash
