name: Go

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19.x
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # pin@v3
        with:
          go-version: "1.19.x"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -cover ./...
