name: Test Action

# Only trigger, when the release workflow succeeded
on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  test_action:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub App Token
        uses: diegosz/github_app_tknzr@main
        id: github_app_tknzr
        with:
          app_id: ${{ secrets.app_id }}
          installation_id: ${{ secrets.installation_id }}
          private_key: ${{ secrets.private_key }}

      - name: Test Github API call
        run: |
          curl -s --fail -H 'Authorization: Bearer ${{ steps.github_app_tknzr.outputs.github_app_token }}' https://api.github.com/
